### ISSUE TITLE
Autoloading only find files in lib but not subdirectories

### ISSUE THREAD

**Issue by gaffneyc** [collectiveidea/twirp-rails#4]
The default auto loading will only find `*_twirp.rb` files that are in the lib directory but won't search for them the way that Rails does. Services tend to be namespaced (e.g. `DMS::FooService`) and the Rails Way:tm: is to have them in a directory named after the module or class they're under. Of course Rails also expects each class to be in its own file so it can deterministically require the file based on the class and it's parent modules which protoc doesn't do.

With this layout it can't find the FooSevice.
```
lib/
lib/dms/foo_twirp.rb
```

I'm not sure if twirp-rails should autoload and `*_twirp.rb` files under lib or a standard is defined for where they should be placed and better documented.

**Comment by danielmorrison** [comment]
Autoloading is very helpful, but I don't know where the best place to look for them is. Very open to opinions.

Should we autoload `**/*_twirp.rb` instead or do something else?

**Comment by danielmorrison** [comment]
So far, I've been mostly using a single `.proto` file, which is probably less interesting than what others do. Open for opinions on best practices there too.

**Comment by danielmorrison** [comment]
A lot of the projects in the prior art section had opinions about running `protoc` for you too. While I'm open to making that easier here, I'm not sure what would be good.

**Comment by gaffneyc** [comment]
Yeah, I really don't know what a good answer is. I know some larger projects have an app's worth of proto definitions scatters across a directory tree. I do like the idea of a single proto file that defines simpler applications.

Another thing in my head is whether it's possible to support code reloading in development for all the generate code. Is there a pattern that makes that easier? I know that `lib` is usually not reloadable but an `app/services` or similar would be expected to be reloadable.

This is the Rake task I use to generate all of the code for my services.
```ruby
# frozen_string_literal: true

desc "Generate Ruby classes for all protobuf definitions in lib"
task :protoc do
  sh "find lib/ -iname *.proto | xargs -r protoc --proto_path=lib --ruby_out=lib"

  # Generate Twirp service definitions for proto files that define services.
  sh "find lib/ -iname *.proto | xargs -r grep -l '^service .* {$' | xargs protoc --proto_path=lib --twirp_ruby_out=lib"

  # Rename `FooServiceService` to `FooService` and `FooServiceClient` to
  # `FooClient`.
  sh "find lib/ -iname *_twirp.rb | xargs -r gsed -i -e 's/ServiceService/Service/g' -e 's/ServiceClient/Client/g'"
end
```
