### ISSUE TITLE
Routes view shows last request

### ISSUE THREAD

**Issue by gaffneyc** [collectiveidea/twirp-rails#5]
When going to `/rails/info/routes` it looks like it's using the `#inspect` output from the handler. Not sure what the expected behavior here is but it doesn't match the format Rails uses (e.g. `foo#action`). The routes view is only available in development mode so there isn't a way to expose data in production.

Two things from seeing this:
- Is something keeping around the most recent request unnecessarily? Could it be exposed through some other means
- Is there something more useful we could be showing 

![/rails/info/routes](https://user-images.githubusercontent.com/7095/220949947-f8d1efcb-efb7-4de2-927c-3e6c2ce5bb38.png)

**Comment by danielmorrison** [comment]
I'll have to see where those come from. If it is as easy as implementing `#inspect`, that'd be nice.
